### ISSUE TITLE
Some hyperlinks of the documentation are broken

### ISSUE THREAD

**Issue by MPvHarmelen** [hbrouwer/dfs-tools#1]
In https://hbrouwer.github.io/dfs-tools/dfs_sentences.html:

> (e.g., using [dfs_localist_word_vectors/2](http://www.swi-prolog.org/pldoc/man?predicate=dfs_localist_word_vectors/2))

And 
> **See also**
>    - [dfs_maps_sentence_onto_semantics/4](http://www.swi-prolog.org/pldoc/man?predicate=dfs_maps_sentence_onto_semantics/4)

**Comment by hbrouwer** [comment]
Thanks Martin, fixed these and a couple of other broken cross-references.
